#!/bin/bash

echo '################################################################################'
echo '# The following output is used to setup aliases to containerized pca commands'
echo '# To apply these changes under bash use a command similar to:'
echo '# eval "$(docker run ncats/pca-reports)"'
echo '#'
echo '# Environment variables:'
echo '# PCA_CONF_DIR, defaults to "/etc/pca" if not set'
echo '# PCA_REPORTS_IMAGE, defaults to "ncats/pca-reports" if not set'
echo '################################################################################'
echo

cd /usr/local/bin

# create output that can be evaled to create aliases for pca-reports commands
for f in pca-*
do
  echo alias $f=\"docker run -it --rm --volume \\\"\\\${PCA_CONF_DIR:-/etc/pca}\\\":/etc/pca --volume \\\`pwd\\\`:/home/pca \\\"\\\${PCA_REPORTS_IMAGE:-ncats/pca-reports}\\\" $f\"
done

# create an alias to start bash in the container
echo alias pca-bash=\"docker run -it --rm --volume \\\"\\\${PCA_CONF_DIR:-/etc/pca}\\\":/etc/pca --volume \\\`pwd\\\`:/home/pca \\\"\\\${PCA_REPORTS_IMAGE:-ncats/pca-reports}\\\" /bin/bash\"
